added implementation requirements - com_io
felixnorden/moppepojkar pull request #8
Opened 2017-09-19 07:51 UTC by AntonKimfors

2017-09-19 08:29 UTC, felixnorden requested changes
CommunicationsMediator:
unsubscribe-method needs correct Reference Type
inputReciever-method should maybe be called 'subscribe'? 🙂  

CommunicationsMediatorImpl:
subscribers-Map needs to have the correct generic type (i.e DataReceivers) 

CommunicatorFactory:
return type of getComInstance should match the CommunicationsMediator interface.

Direction enum:
correct the enum implementation plox ❤️

2017-09-19 10:17 UTC, felixnorden requested changes
Could you remove the .idea folder from the commits? We don't need them in the repository :)

2017-09-19 14:08 UTC, isZumpo commented
Rebased now

2017-09-20 08:11 UTC, felixnorden approved these changes

2017-09-20 08:11 UTC, merged